# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Verify

on:
  pull_request:
    branches: [ 'main', 'release-*' ]
  push:
    branches: [ 'main', 'release-*' ]

jobs:

  verify:
    name: Verify Codegen
    runs-on: ubuntu-latest

    env:
      GOPATH: ${{ github.workspace }}

    steps:
    # https://github.com/mvdan/github-actions-golang#how-do-i-set-up-caching-between-builds
    - uses: actions/cache@v3
      with:
        # In order:
        # * Module download cache
        # * Build cache (Linux)
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set up Go 1.17.x
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
        check-latest: true
    # get the latest ko
    - uses: imjasonh/setup-ko@v0.4

    - name: Install Protoc
      uses: arduino/setup-protoc@v1.1.2
      with:
        version: '3.19.4'

    - name: Install Dependencies
      run: |
        cd $(mktemp -d)
        go install github.com/google/go-licenses@ceb292363ec84358c9a276ef23aa0de893e59b84
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28.0
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2.0
        go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.10.0
        go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@v2.10.0

    - name: Check out code
      uses: actions/checkout@v3
      with:
        path: ./src/github.com/${{ github.repository }}
        fetch-depth: 0

    - name: Update Codegen
      shell: bash
      working-directory: ./src/github.com/${{ github.repository }}
      run: |
        # We limit the depth to 3 mostly to avoid go.mod files that get pulled into `third_party` like some hashicorp repos.
        for dir in $(find . -name go.mod -maxdepth 3 -exec dirname {} \; ); do
          echo "::group:: $dir"
          pushd $dir

          [[ ! -f hack/update-codegen.sh ]] || ./hack/update-codegen.sh

          popd
          echo ::endgroup::
        done

    - name: Verify
      uses: chainguard-dev/actions/nodiff@main
      with:
        path: ./src/github.com/${{ github.repository }}
        fixup-command: "./hack/update-codegen.sh"
