# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Verify

on:
  pull_request:
    branches: [ 'main', 'release-*' ]
  push:
    branches: [ 'main', 'release-*' ]

jobs:

  verify:
    name: Verify Codegen
    runs-on: ubuntu-latest

    env:
      GOPATH: ${{ github.workspace }}

    steps:
    # https://github.com/mvdan/github-actions-golang#how-do-i-set-up-caching-between-builds
    - uses: actions/cache@v3
      with:
        # In order:
        # * Module download cache
        # * Build cache (Linux)
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set up Go 1.18.x
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        check-latest: true

    - name: Check out code
      uses: actions/checkout@v3
      with:
        path: ./src/github.com/${{ github.repository }}
        fetch-depth: 0

    - name: Update Codegen
      shell: bash
      working-directory: ./src/github.com/${{ github.repository }}
      run: |
        ./hack/update-codegen.sh

    - name: Verify
      uses: chainguard-dev/actions/nodiff@main
      with:
        path: ./src/github.com/${{ github.repository }}
        fixup-command: "./hack/update-codegen.sh"
