# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Verify

on:
  pull_request:
    branches: [ 'main', 'release-*' ]
  push:
    branches: [ 'main', 'release-*' ]

jobs:

  verify:
    name: Verify Codegen
    runs-on: ubuntu-latest

    env:
      GOPATH: ${{ github.workspace }}

    steps:
    - name: Check out code
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      with:
        path: ./src/github.com/${{ github.repository }}
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version-file: './src/github.com/${{ github.repository }}/go.mod'
        check-latest: true

    # https://github.com/mvdan/github-actions-golang#how-do-i-set-up-caching-between-builds
    - uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4.1.1
      with:
        # In order:
        # * Module download cache
        # * Build cache (Linux)
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Update Codegen
      shell: bash
      working-directory: ./src/github.com/${{ github.repository }}
      run: |
        ./hack/update-codegen.sh

    - name: Verify
      uses: chainguard-dev/actions/nodiff@main
      with:
        path: ./src/github.com/${{ github.repository }}
        fixup-command: "./hack/update-codegen.sh"
